/**
 * MaT Service
 * Manage A Tenancy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Person (
  /* The value to use when presenting the person's full name */
  presentationName: String,
  /* The role the person has in this task */
  role: String,
  /* The date on which the person was born */
  dateOfBirth: String,
  /* The person's mobile phone number */
  mobileNumber: Option[String] = None,
  /* The person's home phone number */
  homePhoneNumber: Option[String] = None,
  /* The person's work phone number */
  workPhoneNumber: Option[String] = None,
  /* The person's email address */
  email: Option[String] = None
) extends ApiModel


