/**
 * MaT Service
 * Manage A Tenancy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Task (
  /* The id for the task */
  id: UUID,
  /* The time at which the task was initially created */
  createdTime: String,
  /* The category of task */
  category: String,
  /* The specific type of task */
  `type`: String,
  resident: Person,
  address: Address,
  /* The time at which the task is due to be completed */
  dueTime: String,
  /* An optional flag indicating varying degrees of overdue state */
  dueState: Option[String] = None,
  /* The time at which the task was completed */
  completedTime: Option[String] = None,
  stage: String,
  /* Zero or more child tasks */
  children: Option[Seq[Task]] = None,
  parent: Option[Task] = None
) extends ApiModel


