/**
 * MaT Service
 * Manage A Tenancy
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Tenancy (
  /*  */
  `type`: Option[String] = None,
  /* The date on which the tenancy started */
  startDate: Option[String] = None,
  /* The residents occupying the tenancy */
  residents: Option[Seq[Person]] = None
) extends ApiModel


